name: Scheduled Run - Daily

on:
  # push:

  schedule:
    # At 18:45 UTC on everyday (12.15 mid night in Sri Lanka)
    - cron: "15 18 * * *"

  # Enables a button on Actions tab
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          package-manager-cache: false

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: "Update News"
        working-directory: ./python_scripts/
        run: |
          python update_news.py

      - name: "Update Events"
        working-directory: ./python_scripts/
        run: |
          python update_events.py

      - name: "Update Undergraduate Courses"
        working-directory: ./python_scripts/undergraduate_courses
        run: |
          python sync.py

      - name: "Update Taxonomy - Intranet"
        working-directory: ./python_scripts/taxonomy
        run: |
          python intranet.py

      - name: "Update Research Groups"
        working-directory: ./python_scripts/
        run: |
          python research_groups.py

      - name: Format files
        run: |
          npm install --global prettier
          prettier --write "**/*.{js,json,md,yml,yaml,html,css,scss}" \
            --config .prettierrc \
            --ignore-path .prettierignore

      - name: Commit and push into the main branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add --all
          git commit -m "Daily Update by GitHub Actions" || echo "No changes to commit"
          git push
