name: Scheduled Run - Daily

on:
  # push:

  schedule:
    # At 18:45 UTC on everyday (12.15 mid night in Sri Lanka)
    - cron: "15 18 * * *"

  # Enables a button on Actions tab
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Individual scripts executing sub tasks

      - name: "Update News"
        working-directory: ./python_scripts/news_and_events
        run: |
          python update_news.py

      - name: "Update Events"
        working-directory: ./python_scripts/news_and_events
        run: |
          python update_events.py

      - name: "Update Taxonomy - Intranet"
        working-directory: ./python_scripts/taxonomy
        run: |
          python intranet.py

      - name: "Update Taxonomy - Intranet"
        run: |
          cd ./python_scripts/taxonomy/
          python intranet.py

      - name: "Update Research Groups"
        working-directory: ./python_scripts/
        run: |
          python research_groups.py

      - name: Commit and push into the main branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add --all
          git commit -m "Daily Update by GitHub Actions" || echo "No changes to commit"
          git push
