name: Scheduled Run - Publications
on:
  schedule:
    # # At 18:50 UTC on every Monday (12.20 mid night in Sri Lanka)
    - cron: "50 18 * * 1"

  # Enables a button on Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          ref: main

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: "Update list of Publications"
        run: |
          cd ./python_scripts/
          python publications.py

      - name: Commit and push into the main branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add --all
          git commit -m "Publications site was updated by GitHub Actions" || echo "No changes to commit"
          git push
